apiVersion: v1
description: A declarative helm chart for deploying dst-cogynt-workstation-ingest
name: dst-cogynt-workstation-ingest
version: v1.2.17-develop.1
appVersion: v1.2.17-develop.1
maintainers:
- name: Cogility
  email: devops@cogility.com
