{{- $root := . -}}
{{- range $name, $ingress := .Values.ingress -}}
{{- if $ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{- with $ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{ include "common.labels.standard" $root | indent 4 }}
    ingressName: {{ $name }}
  name: {{ include "common.fullname" $root }}-{{ $name }}
spec:
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
{{- range $path := $ingress.paths }}
          - path: {{ $path }}
            backend:
              {{- if hasKey $ingress "service" }}
              serviceName: {{ $ingress.service }}
              {{- else }}
              serviceName: {{ include "common.fullname" $root }}
              {{- end }}
              servicePort: {{ hasKey $ingress "port" | ternary $ingress.port "default" }}
{{- end -}}
{{- with $ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}
