on: [push]

jobs:
  sobelow_job:
    runs-on: ubuntu-latest
    name: Sobelow Job
    steps:
      - uses: actions/checkout@v2
      - id: run-action
        uses: sobelow/action@v1
        with: 
          report: "false"
          flags: "--exit -v -i Config --threshold high"